import fs from 'node:fs';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';

// Export the actual application components; the specimen cannot drift from the UI.
const compiled=ts.transpileModule(fs.readFileSync('src/icons.tsx','utf8'),{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.ESNext}}).outputText;
const temporary=new URL('../.forge-icons-export.mjs',import.meta.url);
fs.writeFileSync(temporary,compiled);
let icons;
try {icons=await import(temporary.href);} finally {fs.unlinkSync(temporary);}
fs.mkdirSync('public/icons',{recursive:true});
const svg=(name,size=24)=>renderToStaticMarkup(React.createElement(icons[name],{size}));
const adapted=new Set(['ArrowRight','ArrowLeft','ArrowUpRight','X','Search']);
const license=fs.readFileSync('public/licenses/Iconoir-MIT.txt','utf8');
for(const name of Object.keys(icons))fs.writeFileSync(`public/icons/${name}.svg`,(adapted.has(name)?`<!-- Adapted from Iconoir. Geometry and presentation modified for ForgeAgent.\n${license}\n-->\n`:'')+svg(name));
const groups=[
 ['01 / 工作空间',[['ForgeMark','锻造标记'],['Home','工作台'],['LayoutList','任务工单'],['Inbox','待我处理'],['FolderGit2','交付包'],['BookOpen','知识索引'],['Activity','运行仪表'],['Project','项目目录'],['Settings','工作空间设置']]],
 ['02 / 执行与信任',[['Workflow','执行流程'],['ShieldCheck','授权印章'],['CheckCircle2','验证通过'],['XCircle','验证失败'],['TriangleAlert','风险提醒'],['Clock3','等待计时'],['GitBranch','检查点分支'],['Layers3','上下文层'],['FlaskConical','评测实验'],['Terminal','执行终端'],['Database','记忆存储'],['Network','工具连接']]],
 ['03 / 文件与操作',Object.keys(icons).filter(n=>!['ForgeMark','Home','LayoutList','Inbox','FolderGit2','BookOpen','Activity','Project','Settings','Workflow','ShieldCheck','CheckCircle2','XCircle','TriangleAlert','Clock3','Clock','GitBranch','Layers3','FlaskConical','Terminal','Database','Network'].includes(n)).map(n=>[n,n])]
];
const total=Object.keys(icons).length;
fs.writeFileSync('public/icon-study.html',`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Forge Marks · 图标样张</title><style>
*{box-sizing:border-box}body{--bg:#f5f4ef;--panel:#fffefa;--text:#253c47;--muted:#60737c;--line:#d8dfdc;--accent:#12689b;margin:0;background:var(--bg);color:var(--text);font:14px/1.6 'Segoe UI','Microsoft YaHei',sans-serif}body.dark{--bg:#121e25;--panel:#192a33;--text:#d9e8e9;--muted:#93acb7;--line:#314550;--accent:#85c8ed}main{max-width:1180px;margin:auto;padding:42px 36px}a{color:inherit;text-underline-offset:4px}.top{display:flex;justify-content:space-between;gap:20px;align-items:center;border-bottom:1px solid var(--line);padding-bottom:20px}.brand{display:flex;align-items:center;gap:12px;font-size:18px;font-weight:650}.edition,.eyebrow{font:11px/1.6 monospace;letter-spacing:2px;color:var(--muted)}header{padding:54px 0 34px;display:grid;grid-template-columns:1fr 260px;gap:40px}h1{font-size:48px;letter-spacing:-2px;font-weight:600;margin:10px 0 12px;line-height:1.2}p{color:var(--muted);max-width:600px}header .hero{display:flex;align-items:center;justify-content:center;gap:30px;background:var(--panel);border:1px solid var(--line);border-radius:3px 28px 3px 3px;color:var(--accent)}.hero svg{width:84px;height:84px}.toolbar{display:flex;align-items:center;gap:10px;flex-wrap:wrap;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:16px 0}.toolbar label{display:flex;gap:9px;align-items:center;margin-right:auto}button,select{font:inherit;color:var(--text);background:var(--panel);border:1px solid var(--line);padding:7px 13px;border-radius:5px;cursor:pointer}button[aria-pressed=true]{background:var(--text);color:var(--bg)}:focus-visible{outline:3px solid var(--accent);outline-offset:4px}h2{font-size:13px;font-weight:550;letter-spacing:1px;margin:32px 0 15px}.grid{display:grid;grid-template-columns:repeat(6,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.tile{min-width:0;min-height:143px;text-decoration:none;background:var(--panel);border-right:1px solid var(--line);border-bottom:1px solid var(--line);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;transition:background .15s}.tile:hover{background:var(--line)}.tile svg{width:var(--size,24px);height:var(--size,24px);color:var(--accent);overflow:visible}.tile span{font-size:12px}.tile small{color:var(--muted);font:10px monospace}.mono .mark-ink{opacity:0}.selected .mark-ink{opacity:.32}footer{margin-top:40px;padding-top:20px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}footer p{max-width:none}.forge-mark{flex-shrink:0}@media(max-width:700px){main{padding:24px 18px}.grid{grid-template-columns:repeat(3,1fr)}header{grid-template-columns:1fr;padding:32px 0;gap:20px}header .hero{padding:24px}h1{font-size:38px}.edition{display:none}}@media(prefers-reduced-motion:reduce){.tile{transition:none}}
</style></head><body><main><div class="top"><div class="brand">${svg('ForgeMark',30)} ForgeAgent <span class="edition">/ MARKS</span></div><a href="/">返回工作空间 ↗</a></div><header><div><div class="eyebrow">FORGE MARKS / 01</div><h1>给每一步执行，<br>一个清楚的标记。</h1><p>折角、切口与局部印色。让工单、授权、检查点和交付包拥有自己的形状，在密集的工作界面中依然易于辨认。</p><span class="edition">24 × 24 GRID · ${total} EXPORTS · EDITABLE SVG</span></div><div class="hero">${svg('ForgeMark',84)}${svg('ShieldCheck',64)}</div></header><div class="toolbar"><label>实际尺寸 <select id="size"><option value="12">12 px</option><option value="16">16 px</option><option value="20">20 px</option><option value="24" selected>24 px</option><option value="32">32 px</option></select></label><button id="mono" aria-pressed="false">单色线稿</button><button id="selected" aria-pressed="false">选中状态</button><button id="theme" aria-pressed="false">深色样张</button></div>${groups.map(([title,entries])=>`<section><h2>${title}</h2><div class="grid">${entries.map(([name,label])=>`<a class="tile" href="/icons/${name}.svg" download="Forge-${name}.svg" aria-label="下载 ${label} SVG">${svg(name)}<span>${label}</span><small>${name}</small></a>`).join('')}</div></section>`).join('')}<footer><p>点击任意图标下载可编辑 SVG。深色按钮仅切换此样张的预览背景；工作空间保持原有主题。图标使用 currentColor，适配所在控件的文字颜色。</p><p>主要业务图形为本项目绘制。ArrowRight、ArrowLeft、ArrowUpRight、X 和 Search 改编自 <a href="https://github.com/iconoir-icons/iconoir">Iconoir</a>，保留 <a href="/licenses/Iconoir-MIT.txt">MIT 许可</a>。其他比较资源：<a href="https://github.com/halfmage/pixelarticons">Pixelarticons</a> / <a href="https://github.com/CyCraft/pepicons">Pepicons</a>。</p></footer></main><script>document.getElementById('size').onchange=e=>document.body.style.setProperty('--size',e.target.value+'px');for(const [id,cls] of [['mono','mono'],['selected','selected'],['theme','dark']])document.getElementById(id).onclick=e=>{const active=document.body.classList.toggle(cls);e.currentTarget.setAttribute('aria-pressed',String(active))};</script></body></html>`);
console.log(`Exported ${total} SVGs and public/icon-study.html`);
