import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ChevronRight, Plus, Search, SlidersHorizontal } from './icons';
import { Button, Dialog, Empty } from './components';
import { pageLabels, type Page } from './types';
import { needsAttention, projects } from './runtime';
import type { Runtime, TaskDraft } from './useRuntime';

export function ActionOverlays({runtime:rt}:{runtime:Runtime}){
 const close=()=>rt.setOverlay(null);
 if(rt.overlay==='create')return <CreateTask runtime={rt} close={close}/>;
 if(rt.overlay==='command')return <CommandSearch runtime={rt} close={close}/>;
 if(rt.overlay==='notifications')return <Dialog title="待办通知" onClose={close}><p className="muted">当前项目范围内，需要你介入的任务。</p>{rt.state.runs.filter(r=>(rt.route.project==='所有项目'||r.project===rt.route.project)&&needsAttention(r)).map(r=><button key={r.id} className="command-result" onClick={()=>rt.app.openRun(r.id)}><span><strong>{r.title}</strong><small className="cell-sub">{r.phase}</small></span><ChevronRight size={17}/></button>)}<div className="form-footer"><Button onClick={()=>rt.app.navigate('inbox')}>打开待我处理<ArrowRight size={16}/></Button></div></Dialog>;
 return null;
}
function CreateTask({runtime:rt,close}:{runtime:Runtime;close:()=>void}){
 const key='forge-task-draft-v2';const [draft,setDraft]=useState<TaskDraft>(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved)return saved}catch{}return{title:'',description:'',criteria:'回归测试通过\n产物与验证凭证版本一致',scope:'仅修改 src 和 tests；禁止访问生产环境',project:rt.route.project==='所有项目'?(rt.state.projects?.[0]?.id||'runtime-lab'):rt.route.project,model:'configured',allowedPaths:'src,tests',budget:rt.app.settings.budget,skills:rt.state.skills.filter(s=>s.enabled).map(s=>s.id)}});
 const [errors,setErrors]=useState<Record<string,string>>({});const [advanced,setAdvanced]=useState(false);const [busy,setBusy]=useState(false);const submitted=useRef(false);
 useEffect(()=>{if(!submitted.current)try{localStorage.setItem(key,JSON.stringify(draft))}catch{}},[draft]);
 const field=<K extends keyof TaskDraft>(key:K,value:TaskDraft[K])=>{setDraft(d=>({...d,[key]:value}));setErrors(e=>({...e,[key]:''}))};
 async function submit(e:React.FormEvent){e.preventDefault();if(submitted.current)return;const next:Record<string,string>={};for(const k of ['title','description','criteria','scope'] as const)if(!draft[k].trim())next[k]='请填写此项，任务需要明确的目标与边界。';if(!Number.isFinite(draft.budget)||draft.budget<.1||draft.budget>100)next.budget='预算应为 0.1–100 USD。';setErrors(next);if(Object.keys(next).length){if(next.budget)setAdvanced(true);return}submitted.current=true;setBusy(true);try{await rt.create({...draft,title:draft.title.trim()});localStorage.removeItem(key)}catch(e){submitted.current=false;setBusy(false);setErrors({submit:(e as Error).message})}}
 return <Dialog title="创建任务" subtitle="明确目标、验收条件和允许的修改范围。" onClose={()=>{if(!busy)close()}} wide><form onSubmit={submit} noValidate>
  <label className="field">任务目标<input aria-label="任务目标" aria-required="true" autoFocus maxLength={120} value={draft.title} onChange={e=>field('title',e.target.value)} placeholder="例如：修复认证模块的并发刷新问题" aria-invalid={!!errors.title}/>{errors.title&&<span className="field-error" role="alert">{errors.title}</span>}</label>
  <label className="field">项目<select aria-label="项目" value={draft.project} onChange={e=>field('project',e.target.value)}>{Array.from(new Set([...(rt.state.projects||[]).map(p=>p.id),...rt.state.runs.map(r=>r.project)])).map(p=><option key={p}>{p}</option>)}</select></label>
  <label className="field">任务说明<textarea aria-label="任务说明" aria-required="true" value={draft.description} maxLength={3000} onChange={e=>field('description',e.target.value)} placeholder="描述问题背景、期望行为与相关线索…" aria-invalid={!!errors.description}/>{errors.description&&<span className="field-error" role="alert">{errors.description}</span>}</label>
  <div className="field-row"><label className="field">验收条件<textarea aria-label="验收条件" aria-required="true" value={draft.criteria} onChange={e=>field('criteria',e.target.value)} placeholder="每行一项可检查的条件" aria-invalid={!!errors.criteria}/>{errors.criteria&&<span className="field-error">{errors.criteria}</span>}</label><label className="field">允许修改的范围<textarea aria-label="允许修改的范围" aria-required="true" value={draft.scope} onChange={e=>field('scope',e.target.value)} aria-invalid={!!errors.scope}/>{errors.scope&&<span className="field-error">{errors.scope}</span>}</label></div>
  <label className="field">允许写入的路径（逗号分隔）<input aria-label="允许写入的路径" value={draft.allowedPaths||'src,tests'} onChange={e=>field('allowedPaths',e.target.value)}/><small>按路径执行权限检查；任务描述不会扩大此范围。</small></label><button className="advanced-toggle" type="button" aria-expanded={advanced} onClick={()=>setAdvanced(!advanced)}><SlidersHorizontal size={16}/>运行配置<span>{draft.model} · ${draft.budget.toFixed(2)} 上限</span></button>
  {advanced&&<div className="advanced-fields"><div className="field-row"><label className="field">模型<select aria-label="模型" value={draft.model} onChange={e=>field('model',e.target.value)}><option value="configured">已配置的服务端模型</option><option value="fixture">确定性测试模型（仅 Runtime Lab）</option></select></label><label className="field">预算上限（USD）<input aria-label="预算上限（USD）" type="number" min=".1" max="100" step=".1" value={draft.budget} onChange={e=>field('budget',Number(e.target.value))}/>{errors.budget&&<span className="field-error">{errors.budget}</span>}</label></div><div className="field">任务技能快照<div className="selection-list">{rt.state.skills.filter(s=>s.enabled).map(s=><label className="selection-item" key={s.id}><input type="checkbox" checked={draft.skills.includes(s.id)} onChange={()=>field('skills',draft.skills.includes(s.id)?draft.skills.filter(x=>x!==s.id):[...draft.skills,s.id])}/>{s.name} <small>v{s.version}</small></label>)}</div><small>创建时锁定技能与记忆；以后修改全局配置不改变此任务。</small></div></div>}
  {advanced&&<div className="selection-list"><label className="selection-item"><input type="checkbox" checked={!!draft.allowExternal} onChange={e=>field('allowExternal',e.target.checked)}/>允许申请外部写入（每个操作另行审批）</label><label className="selection-item"><input type="checkbox" checked={!!draft.allowDelegation} onChange={e=>field('allowDelegation',e.target.checked)}/>允许委派受限子任务</label></div>}
  {errors.submit&&<div className="notice warning" role="alert">{errors.submit}</div>}
  <div className="form-footer"><span className="muted">任务保存到服务端 · 草稿保存在浏览器</span><div className="button-row"><Button onClick={close} disabled={busy}>保存草稿并关闭</Button><Button primary type="submit" disabled={busy}><Plus size={16}/>{busy?'正在创建…':'创建任务'}</Button></div></div>
 </form></Dialog>
}
function CommandSearch({runtime:rt,close}:{runtime:Runtime;close:()=>void}){
 const [q,setQ]=useState('');const [all,setAll]=useState(false);const pages=Object.entries(pageLabels).filter(([p,l])=>p!=='task'&&(l.includes(q)||p.includes(q.toLowerCase())));
 const runs=rt.state.runs.filter(r=>(all||rt.route.project==='所有项目'||r.project===rt.route.project)&&`${r.title} ${r.id} ${r.project}`.toLowerCase().includes(q.toLowerCase())).slice(0,8);
 return <Dialog title="快速前往" subtitle="搜索页面或任务 · Ctrl / ⌘ K" onClose={close}><label className="search-field command-search"><Search size={18}/><input aria-label="全局搜索" value={q} onChange={e=>setQ(e.target.value)} placeholder="任务名称、编号或页面…" autoFocus/></label><label className="check-label"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>搜索所有项目</label><div className="command-results">{pages.map(([page,label])=><button className="command-result" key={page} onClick={()=>rt.app.navigate(page as Page)}><span>{label}</span><ChevronRight size={16}/></button>)}{runs.map(r=><button className="command-result" key={r.id} onClick={()=>rt.app.openRun(r.id)}><span>{r.title}<small className="cell-sub">{r.id} · {r.project}</small></span><ArrowRight size={16}/></button>)}{!pages.length&&!runs.length&&<Empty title="没有匹配结果" description="调整关键词或搜索范围，不会影响现有任务。"/>}</div></Dialog>
}


