import { useEffect, useState } from 'react';
import { api } from './api';
import type { AppController } from './types';
import { Button, Dialog, Empty, Heading, Metric, Panel } from './components';

function useRemote(path:string,interval=0){const [data,setData]=useState<any>(null);const [error,setError]=useState('');const reload=async()=>{try{setData(await api(path));setError('')}catch(e){setError((e as Error).message)}};useEffect(()=>{void reload();if(interval){const id=setInterval(reload,interval);return()=>clearInterval(id)}},[path]);return {data,error,reload}}

export function JsonForm({title,path,initial,onDone}:{title:string;path:string;initial:object;onDone:()=>void}){
 const [body,setBody]=useState(JSON.stringify(initial,null,2));const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 return <Dialog title={title} onClose={onDone} wide><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await api(path,'POST',JSON.parse(body));onDone()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label className="field">配置内容<textarea aria-label="配置内容" rows={17} value={body} onChange={e=>setBody(e.target.value)} spellCheck={false}/></label>{error&&<p role="alert" className="notice warning">{error}</p>}<div className="form-footer"><Button onClick={onDone}>关闭</Button><Button primary type="submit" disabled={busy}>{busy?'正在保存…':'保存到服务端'}</Button></div></form></Dialog>
}

export function Tools({app}:{app:AppController}){
 const {data,error,reload}=useRemote('/connections');const [diagnostic,setDiagnostic]=useState<any>(null);const [busy,setBusy]=useState(false);const [adding,setAdding]=useState(false);
 async function test(){setBusy(true);try{setDiagnostic(await api('/diagnostics'))}catch(e){app.notify((e as Error).message)}finally{setBusy(false)}}
 return <><Heading eyebrow="CAPABILITIES" title="工具连接" description="检查执行环境并登记受控的 MCP / A2A 连接。"><Button onClick={test} disabled={busy}>{busy?'正在检查…':'检查实际连接'}</Button><Button primary onClick={()=>setAdding(true)}>登记连接</Button></Heading>{error&&<p role="alert">{error}</p>}<Panel title="内置工具"><div className="panel-pad"><p>repo.list · repo.read · repo.write · tests.run</p><p className="muted">写入受路径和前置摘要约束。命令只在无网 Docker 沙箱执行。</p></div></Panel>{diagnostic&&<Panel title="实时环境检查"><div className="panel-pad"><p>模型：{diagnostic.model.configured?'已配置':'未配置'} · 沙箱：{diagnostic.sandbox.ready?'可用':'不可用'}</p><pre className="code-block">{JSON.stringify(diagnostic,null,2)}</pre></div></Panel>}{data?.map((c:any)=><Panel title={`${c.name} · ${c.status}`} key={c.id}><div className="panel-pad"><p>{c.kind.toUpperCase()} · {c.protocol}</p><p className="mono wrap">{c.url}</p><p className="muted">外部写入在任务动作账本中准备，再单独审批。</p></div></Panel>)}{data?.length===0&&<Empty title="尚未登记外部连接" description="管理员先在服务端配置允许访问的主机，再登记具体协议端点。"/>}{adding&&<JsonForm title="登记外部连接" path="/connections" initial={{name:'My MCP server',kind:'mcp',protocol:'2025-11-25',url:'https://example.com/mcp'}} onDone={()=>{setAdding(false);void reload()}}/>}</>
}

export function Evaluations({app}:{app:AppController}){
 const {data,error,reload}=useRemote('/evaluations',2000);const [busy,setBusy]=useState(false);
 const [form,setForm]=useState<'dataset'|'experiment'|null>(null);const datasets=useRemote('/evaluation-datasets');
 return <><Heading eyebrow="EVALUATIONS" title="评测实验" description="固定任务集与配对运行结果。"><Button onClick={()=>setForm('dataset')}>登记任务集</Button><Button onClick={()=>setForm('experiment')}>新建配对实验</Button><Button primary disabled={busy} onClick={async()=>{setBusy(true);try{await api('/evaluations','POST',{repetitions:3,seed:42});await reload()}catch(e){app.notify((e as Error).message)}finally{setBusy(false)}}}>运行契约评测</Button></Heading>{error&&<p role="alert">{error}</p>}{datasets.data?.length>0&&<Panel title="已登记任务集">{datasets.data.map((d:any)=><div className="list-row" key={d.id}><strong>{d.id}</strong><span>{d.split} · {d.cases.length} 个任务</span></div>)}</Panel>}{data?.slice().reverse().map((e:any)=><Panel key={e.id} title={`${e.dataset} · ${e.status}`}><div className="panel-pad"><p>{e.successes} / {e.total} 通过 · 模型 {e.model||'未配置'}</p>{e.kind==='paired'?<><p className="muted">独立任务：{e.independent_cases} · 每配置重复：{e.repetitions}</p><pre className="code-block">{JSON.stringify({configurations:e.summaries,comparisons:e.comparisons},null,2)}</pre></>:<p className="muted">Wilson 95% 区间：{e.wilson_95_ci.map((x:number)=>(x*100).toFixed(1)+'%').join(' – ')}。重复确定性用例不视为独立任务样本。</p>}{e.results.map((r:any)=><div className="list-row" key={r.id}><span className="mono wrap">{r.case_id?`${r.case_id} / ${r.config}`:r.id}</span><span>{r.status}</span><Button onClick={()=>app.openRun(r.id)}>执行记录</Button></div>)}<Button onClick={()=>app.download(`evaluation-${e.id}.json`,JSON.stringify(e,null,2))}>导出原始报告</Button></div></Panel>)}{data?.length===0&&<Empty title="尚无评测结果" description="任务集与实验结果将保存在工作空间。"/>}{form&&<JsonForm title={form==='dataset'?'登记评测任务集':'新建配对实验'} path={form==='dataset'?'/evaluation-datasets':'/experiments'} initial={form==='dataset'?{id:'local-tasks@1',split:'development',source:'Project acceptance contracts',cases:[{id:'addition',project_id:'runtime-lab',task:{goal:'Fix addition',allowed_paths:['src']},budget:{max_cost_usd:'0.10'}}]}:{dataset_id:datasets.data?.[0]?.id||'local-tasks@1',model:'fixture',configurations:[{name:'baseline',harness:{context_policy:'full'}},{name:'elision',harness:{context_policy:'elide'}}],repetitions:3,seed:42,max_total_cost_usd:'10',noninferiority_margin:0.02,max_cost_ratio:1}} onDone={()=>{setForm(null);void reload();void datasets.reload()}}/>}</>
}

export function Observability({app}:{app:AppController}){
 const {data,error}=useRemote('/metrics',3000);
 return <><Heading eyebrow="OBSERVABILITY" title="运行观测" description="从持久执行记录统计任务、费用与待对账动作。">{data&&<Button onClick={()=>app.download('runtime-metrics.json',JSON.stringify(data,null,2))}>导出指标</Button>}</Heading>{error&&<p role="alert">{error}</p>}{data&&<div className="metric-grid"><Metric label="运行次数" value={data.runs} note="当前租户"/><Metric label="已验证完成" value={data.succeeded} note="凭证通过且效果已结算"/><Metric label="累计费用" value={`$${data.cost_usd.toFixed(6)}`} note={`另有 $${data.reserved_usd.toFixed(6)} 预留`}/><Metric label="未知动作" value={data.unknown_actions} note="需要对账"/></div>}<Panel title="任务执行记录">{app.runs.map(r=><div className="list-row" key={r.id}><div className="grow"><strong>{r.title}</strong><p className="muted">{r.status} · {r.steps} 个动作 · {r.duration}</p></div><Button onClick={()=>app.openRun(r.id)}>查看详情</Button></div>)}</Panel><p className="muted">Prometheus 指标：/metrics。业务事件永久按序号读取；诊断 Trace 不参与状态一致性。</p></>
}

export function Settings({app}:{app:AppController}){
 const [draft,setDraft]=useState(app.settings);const [adding,setAdding]=useState(false);const [token,setToken]=useState('');const projects=useRemote('/projects');
 return <><Heading eyebrow="WORKSPACE" title="工作空间设置" description="预算、并发配置保存在服务端；已创建任务保留其固定契约。"/><form onSubmit={e=>{e.preventDefault();app.saveSettings({...draft,redact:true})}}><Panel title="运行设置"><div className="panel-pad field-row"><label className="field">默认任务预算（USD）<input type="number" min="0.1" max="100" step="0.1" value={draft.budget} onChange={e=>setDraft({...draft,budget:Number(e.target.value)})}/></label><label className="field">租户并发上限<select value={draft.concurrency} onChange={e=>setDraft({...draft,concurrency:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="panel-pad"><Button primary type="submit">保存设置</Button></div></Panel></form><Panel title="已登记项目" action={<Button onClick={()=>setAdding(true)}>登记项目</Button>}>{projects.error&&<p>{projects.error}</p>}{projects.data?.map((p:any)=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><p className="muted">{p.id} · 验收 {p.acceptance?.id} · {Object.keys(p.baseline||{}).length} 个基线文件</p></div></div>)}</Panel><Panel title="模型与执行环境"><div className="panel-pad"><p>在服务端 .env 中配置模型提供方、精确模型 ID、API 密钥与单价。密钥不会发送到前端。</p><p>启动沙箱前构建 sandbox/Dockerfile；真实模型生成的代码只在隔离容器运行。</p><Button onClick={()=>app.navigate('tools')}>检查连接与环境</Button></div></Panel><Panel title="共享服务登录"><div className="panel-pad"><p className="muted">本机模式不需要令牌。OIDC 部署使用当前身份提供方签发的访问令牌，仅保存于本次浏览器会话。</p><label className="field">OIDC 访问令牌<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)}/></label><Button onClick={()=>{if(token)sessionStorage.setItem('forge-access-token',token);else sessionStorage.removeItem('forge-access-token');setToken('');location.reload()}}>应用会话身份</Button></div></Panel>{adding&&<JsonForm title="登记项目基线与验收" path="/projects" initial={{id:'my-project-v1',name:'My Project',baseline:{'src/example.py':'def answer():\n    return 0\n'},acceptance_id:'answer@1',verification_argv:['python','-m','unittest','discover','-s','hidden_tests'],protected_tests:{'hidden_tests/test_answer.py':'import unittest\nfrom src.example import answer\nclass Contract(unittest.TestCase):\n    def test_answer(self):\n        self.assertEqual(answer(),42)\n'}}} onDone={()=>{setAdding(false);void projects.reload()}}/>}</>
}
