import { useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronDown, ChevronRight, Clock3, Code2, FileCheck2, FileText, FlaskConical, Project, GitBranch, Inbox, Layers3, ListFilter, MoreHorizontal, Pause, Play, Plus, Search, ShieldCheck, SlidersHorizontal, Terminal, TriangleAlert, Workflow } from './icons';
import { Button, Dialog, Empty, Heading, Panel } from './components';
import { WorkbenchView } from './Views';
import type { Runtime, Scenario } from './useRuntime';
import { needsAttention, relativeTime, statusText, waitLabels, type Execution, type RunEvent } from './runtime';
import { TaskWorkspace } from './TaskWorkspace';

export function RunBadge({run:r}:{run:Execution}){return <span className={`run-badge badge-${r.status.toLowerCase()}`}>{r.status==='SUCCEEDED'?<CheckCircle2 size={14}/>:r.status==='FAILED'?<TriangleAlert size={14}/>:r.status==='PAUSED'?<Pause size={13}/>:r.status==='CANCELLING'?<Clock3 size={14}/>:<span className="status-dot"/>}{statusText[r.status]}</span>}
export function useFollowing(){const [saved,setSaved]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('forge-twitter-bookmarks')||'[]')}catch{return []}});return {saved,toggle:(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);try{localStorage.setItem('forge-twitter-bookmarks',JSON.stringify(next))}catch{}}}}
export function nextStep(r:Execution){return r.status==='SUCCEEDED'?{label:'查看交付',tab:'verification'}:needsAttention(r)?{label:r.waitReason==='APPROVAL'?'审查操作':r.unknownEffect?'确认外部结果':'诊断与恢复',tab:r.waitReason==='APPROVAL'?'review':'recovery'}:{label:'查看执行',tab:'timeline'}}
export function TaskRow({run:r,runtime:rt,compact=false}:{run:Execution;runtime:Runtime;compact?:boolean}){
 const next=nextStep(r);return <article className={`task-row ${compact?'compact':''}`} data-run={r.id}>
  <div className="task-row-top"><div className="task-row-title"><button onClick={()=>rt.app.openRun(r.id)}>{r.title}</button><div className="task-meta"><RunBadge run={r}/><span>{r.project}</span><span className="mono">{r.id}</span><span>{relativeTime(r.updatedAt)}</span></div></div><Button primary={needsAttention(r)} onClick={()=>rt.openTask(r.id,next.tab)}>{next.label}<ArrowUpRight size={15}/></Button></div>
  {!compact&&<p className={`task-phase ${needsAttention(r)?'attention-text':''}`}>{needsAttention(r)?<TriangleAlert size={15}/>:<GitBranch size={15}/>}<span>{r.waitReason?waitLabels[r.waitReason]:r.phase}</span><span className="task-cost">${r.cost.toFixed(2)} / ${r.budget.toFixed(2)}</span></p>}
 </article>
}
function SectionTitle({title,count,action}:{title:string;count?:number;action?:React.ReactNode}){return <div className="section-title"><h2>{title}{count!==undefined&&<span>{count}</span>}</h2>{action}</div>}
export function ConsoleContent({runtime:rt}:{runtime:Runtime}){
 const {route,state,app}=rt;const scoped=state.runs.filter(r=>route.project==='所有项目'||r.project===route.project);
 if(route.page==='task')return <TaskWorkspace runtime={rt}/>;
 if(route.page==='overview')return <Overview runtime={rt} runs={scoped}/>;
 if(route.page==='runs')return <TaskList runtime={rt} runs={scoped}/>;
 if(['inbox','approvals','recovery'].includes(route.page))return <InboxView runtime={rt} runs={scoped}/>;
 if(route.page==='artifacts')return <Deliveries runtime={rt} runs={scoped}/>;
 if(route.page==='context')return <><Heading eyebrow="" title="上下文检查" description="选择任务，检查创建时锁定的输入、技能版本和原始观察。"/>{scoped.map(r=><div className="task-row" key={r.id}><div className="task-row-top"><strong>{r.title}</strong><Button onClick={()=>rt.openTask(r.id,'context')}>检查输入<ArrowRight size={16}/></Button></div></div>)}</>;
 const scopedApp={...app,runs:scoped,artifacts:state.artifacts.filter(a=>scoped.some(r=>r.id===a.runId)),memories:state.memories.filter(m=>!m.project||route.project==='所有项目'||m.project===route.project)};
 return <WorkbenchView key={`${route.page}-${route.project}`} app={scopedApp}/>;
}
function Overview({runtime:rt,runs}:{runtime:Runtime;runs:Execution[]}){
 const urgent=runs.filter(needsAttention);const active=runs.filter(r=>['ACTIVE','QUEUED','CANCELLING'].includes(r.status)||(r.status==='WAITING'&&!needsAttention(r)));const done=runs.filter(r=>r.status==='SUCCEEDED');
 return <><Heading eyebrow="" title="工作台" description="任务的下一步，清楚地在这里。"><Button onClick={()=>rt.scenario('active')}><FlaskConical size={16}/>运行契约示例</Button><Button primary onClick={rt.app.newRun}><Plus size={17}/>创建任务</Button></Heading>
  <div className="overview-stats"><button onClick={()=>rt.app.navigate('inbox')}><span className="stat-symbol amber"><Inbox size={20}/></span><div><span>需要你处理</span><strong>{urgent.length.toString().padStart(2,'0')}</strong></div><ChevronRight size={16}/></button><button onClick={()=>{rt.app.navigate('runs')}}><span className="stat-symbol blue"><Activity size={20}/></span><div><span>正在推进</span><strong>{active.length.toString().padStart(2,'0')}</strong></div><ChevronRight size={16}/></button><button onClick={()=>rt.app.navigate('artifacts')}><span className="stat-symbol green"><FileCheck2 size={20}/></span><div><span>已验证交付</span><strong>{done.length.toString().padStart(2,'0')}</strong></div><ChevronRight size={16}/></button></div>
  <SectionTitle title="需要你决定" count={urgent.length} action={<button className="text-action" onClick={()=>rt.app.navigate('inbox')}>全部待办<ArrowRight size={15}/></button>}/>
  <div className="attention-list">{urgent.slice(0,2).map(r=>{const a=rt.state.approvals.find(a=>a.runId===r.id&&a.status==='pending');const next=nextStep(r);return <article className="attention-row" key={r.id}><span className="attention-icon">{r.waitReason==='APPROVAL'?<ShieldCheck size={21}/>:<TriangleAlert size={21}/>}</span><div><span className="attention-label">{r.waitReason==='APPROVAL'?'授权请求':r.unknownEffect?'结果待确认':'恢复诊断'} · {r.project}</span><h3>{a?.title||r.title}</h3><p>{a?.impact||r.phase}</p></div><Button primary onClick={()=>rt.openTask(r.id,next.tab)}>{next.label}<ArrowRight size={15}/></Button></article>})}{!urgent.length&&<div className="all-clear"><CheckCircle2 size={22}/><div><strong>当前没有阻塞你的工作</strong><p>新的审批、故障或待确认结果会出现在这里。</p></div></div>}</div>
  <SectionTitle title="活跃任务" count={active.length} action={<button className="text-action" onClick={()=>rt.app.navigate('runs')}>查看任务<ArrowRight size={15}/></button>}/>
  <div className="task-list">{active.slice(0,4).map(r=><TaskRow key={r.id} run={r} runtime={rt}/>)}{!active.length&&<div className="quiet-state"><Workflow size={22}/><span>当前没有活跃任务。</span><Button onClick={rt.app.newRun}>创建任务</Button></div>}</div>
  <SectionTitle title="近期事件" action={<span className="small-note">按事件发生时间 · 持久记录</span>}/>
  <EventStream key={rt.route.project} runtime={rt} events={rt.state.events.filter(e=>runs.some(r=>r.id===e.runId))} compact/>

 </>
}
function TaskList({runtime:rt,runs}:{runtime:Runtime;runs:Execution[]}){
 const {saved}=useFollowing();const [density,setDensity]=useState(()=>localStorage.getItem('forge-density')||'standard');const filters=[['all','全部'],['active','推进中'],['attention','需要处理'],['done','已完成'],['following','已关注']];
 const list=runs.filter(r=>(rt.route.filter==='all'||(rt.route.filter==='active'&&['ACTIVE','WAITING','QUEUED','CANCELLING'].includes(r.status))||(rt.route.filter==='attention'&&needsAttention(r))||(rt.route.filter==='done'&&r.status==='SUCCEEDED')||(rt.route.filter==='following'&&saved.includes(r.id)))&&`${r.title} ${r.id}`.toLowerCase().includes(rt.route.q.toLowerCase()));
 return <><Heading eyebrow="" title="任务" description="按任务管理目标、执行与交付。"><Button primary onClick={rt.app.newRun}><Plus size={17}/>创建任务</Button></Heading><div className="list-toolbar"><label className="search-field"><Search size={17}/><input aria-label="搜索任务" placeholder="搜索任务名称或编号" value={rt.route.q} onChange={e=>rt.app.setSearch(e.target.value)}/></label><label className="density-control"><SlidersHorizontal size={16}/><select aria-label="信息密度" value={density} onChange={e=>{setDensity(e.target.value);localStorage.setItem('forge-density',e.target.value)}}><option value="standard">标准视图</option><option value="compact">紧凑视图</option></select></label></div><div className="filter-tabs" role="tablist" aria-label="任务筛选">{filters.map(([id,label])=><button role="tab" aria-selected={rt.route.filter===id} key={id} className={rt.route.filter===id?'active':''} onClick={()=>rt.setFilter(id)}>{label}</button>)}<span>{list.length} 个任务</span></div><div className="task-list">{list.map(r=><TaskRow key={r.id} run={r} runtime={rt} compact={density==='compact'}/>)}{!list.length&&<Empty title={runs.length?'没有匹配任务':'这个项目还没有任务'} description={runs.length?'调整搜索或筛选条件，现有任务不会被删除。':'创建任务后，可在这里跟踪执行与交付。'}><Button onClick={rt.clearFilters}>清除筛选</Button></Empty>}</div>{rt.state.next_cursor&&<Button onClick={()=>void rt.loadMore()}>加载更多任务</Button>}</>
}
function InboxView({runtime:rt,runs}:{runtime:Runtime;runs:Execution[]}){
 const [filter,setFilter]=useState('all');const history=rt.route.page==='approvals';const recovery=rt.route.page==='recovery';
 const items=runs.filter(r=>needsAttention(r)&&(filter==='all'||(filter==='approval'?r.waitReason==='APPROVAL':r.waitReason!=='APPROVAL'))&&(recovery?r.waitReason!=='APPROVAL':true));
 return <><Heading eyebrow="" title={history?'审批记录':recovery?'恢复诊断':'待我处理'} description={history?'每个决定都关联明确的操作目标与任务版本。':'集中处理审批、执行故障与未知外部效果。'}/>{!history&&<div className="filter-tabs">{[['all','全部事项'],['approval','授权审批'],['recovery','恢复与确认']].map(([id,l])=><button className={filter===id?'active':''} onClick={()=>setFilter(id)} key={id}>{l}</button>)}</div>}{history?<div className="task-list">{rt.state.approvals.filter(a=>runs.some(r=>r.id===a.runId)).map(a=><div className="task-row" key={a.id}><div className="task-row-top"><div><h3>{a.title}</h3><p className="muted">{a.target} · v{a.version}</p><span className="decision-status">{({pending:'待审查',approved:'已批准',denied:'已拒绝',expired:'已失效'})[a.status]}</span>{a.reason&&<p className="small-note">{a.reason}</p>}</div><Button onClick={()=>rt.openTask(a.runId,'review')}>查看记录<ArrowRight size={16}/></Button></div></div>)}</div>:<div className="task-list">{items.map(r=><TaskRow key={r.id} run={r} runtime={rt}/>)}{!items.length&&<Empty title="当前没有待处理事项" description="新的审批、故障和结果待确认事项会出现在这里。"><Button onClick={()=>rt.app.navigate('runs')}>查看任务</Button></Empty>}</div>}</>
}
function Deliveries({runtime:rt,runs}:{runtime:Runtime;runs:Execution[]}){
 const [filter,setFilter]=useState('all');const items=rt.state.artifacts.filter(a=>runs.some(r=>r.id===a.runId)&&(filter==='all'||(filter==='verified'?a.verified:!a.verified)));
 return <><Heading eyebrow="" title="交付物" description="查看文件变更、验证结果与版本绑定的凭证。"><Button onClick={()=>rt.app.download('artifact-manifest.json',JSON.stringify(items.map(({content,...a})=>a),null,2))}><ArrowDownToLine size={16}/>导出清单</Button></Heading><div className="filter-tabs">{[['all','全部产物'],['verified','验证通过'],['pending','待验证']].map(([id,l])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{l}</button>)}</div><div className="delivery-list">{items.map(a=><article key={a.id} className="delivery-row"><span className={`file-icon ${a.verified?'verified':''}`}>{a.type==='代码补丁'?<Code2 size={23}/>:<FileText size={23}/>}</span><div><button className="delivery-name" onClick={()=>rt.openTask(a.runId,'changes')}>{a.name}</button><p>{a.runId} · v{a.version} · {a.type}</p><span className={`verification-label ${a.verified?'passed':''}`}>{a.verified?<CheckCircle2 size={14}/>:<Clock3 size={14}/>} {a.verified?'验证凭证有效':'尚未验证'}</span></div><Button onClick={()=>rt.openTask(a.runId,'changes')}>预览<ArrowUpRight size={15}/></Button></article>)}{!items.length&&<Empty title="没有符合条件的交付物" description="任务生成的文件与验证报告会保存在这里。"/>}</div></>
}
const eventIcons={task:Workflow,plan:GitBranch,tool:Terminal,approval:ShieldCheck,recovery:TriangleAlert,verification:FileCheck2,cancel:Pause};
export function EventStream({runtime:rt,events,compact=false}:{runtime:Runtime;events:RunEvent[];compact?:boolean}){
 const [visible,setVisible]=useState(()=>new Set(events.map(e=>e.id)));const [follow,setFollow]=useState(false);const [filter,setFilter]=useState('all');const top=useRef<HTMLDivElement>(null);const bottom=useRef<HTMLDivElement>(null);
 const fresh=events.filter(e=>!visible.has(e.id));
 useEffect(()=>{if(fresh.length&&follow&&window.innerHeight+window.scrollY>=document.documentElement.scrollHeight-120){setVisible(new Set(events.map(e=>e.id)));requestAnimationFrame(()=>bottom.current?.scrollIntoView({block:'end',behavior:'instant'}))}},[events,follow]);
 const displayed=events.filter(e=>visible.has(e.id)&&(filter==='all'||e.kind===filter)).slice(0,compact?6:events.length);
 return <div className="event-stream" ref={top}>{!compact&&<div className="event-controls"><select aria-label="事件类型" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">所有事件</option><option value="tool">工具观察</option><option value="approval">授权决定</option><option value="verification">验收验证</option><option value="recovery">恢复与故障</option></select><label className="check-label"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/>位于底部时跟随更新</label></div>}{fresh.length>0&&<button className="new-events" onClick={()=>{setVisible(new Set(events.map(e=>e.id)));top.current?.scrollIntoView({block:'start',behavior:'instant'})}}>{fresh.length} 条新事件 · 点击查看<ChevronDown size={16}/></button>}{displayed.map(e=>{const Icon=eventIcons[e.kind];const r=rt.state.runs.find(r=>r.id===e.runId);return <article className={`event-row event-${e.kind}`} key={e.id}><span className="event-icon"><Icon size={17}/></span><div><div className="event-title"><h3>{e.title}</h3><time title={new Date(e.time).toLocaleString('zh-CN')}>{relativeTime(e.time)}</time></div>{compact?<><p>{r?.title}</p><button className="text-action" onClick={()=>rt.app.openRun(e.runId)}>{e.runId}<ArrowUpRight size={13}/></button></>:<details><summary>查看记录与原始观察</summary><pre className="code-block">{e.detail}</pre><small className="mono">事件 {e.id.slice(0,8)} · {new Date(e.time).toLocaleString('zh-CN')}</small></details>}</div></article>})}{!displayed.length&&<Empty title="当前没有此类事件" description="事件发生后会显示在这里，历史记录不会被覆盖。"/>}{!compact&&rt.state.event_next_cursor&&<Button onClick={()=>void rt.loadOlderEvents()}>加载更早记录</Button>}<div ref={bottom}/></div>
}
export function Inspector({runtime:rt}:{runtime:Runtime}){
 const r=rt.state.runs.find(r=>r.id===rt.route.id);const runs=rt.state.runs.filter(r=>rt.route.project==='所有项目'||r.project===rt.route.project);const urgent=runs.filter(needsAttention);const total=runs.reduce((a,r)=>a+r.cost,0);
 if(r)return <div className="inspector-content"><div className="inspector-heading"><span>任务信息</span><span className="mono">{r.id}</span></div><section className="inspector-section"><h3>下一步</h3><p>{r.cancelRequested?'等待在途操作结算；取消不会撤销已发生的外部变更。':r.waitReason?waitLabels[r.waitReason]:r.status==='SUCCEEDED'?'验收已完成，可检查交付物与验证凭证。':r.phase}</p>{needsAttention(r)&&<Button onClick={()=>rt.setTab(nextStep(r).tab)}>{nextStep(r).label}<ArrowRight size={15}/></Button>}</section><section className="inspector-section"><h3>执行状态</h3><RunBadge run={r}/><dl><dt>当前阶段</dt><dd>{r.phase}</dd><dt>最近更新</dt><dd>{relativeTime(r.updatedAt)}</dd><dt>等待原因</dt><dd>{r.waitReason?waitLabels[r.waitReason]:'无'}</dd></dl></section><section className="inspector-section"><h3>预算与耗时</h3><div className="budget-value"><strong>${r.cost.toFixed(2)}</strong><span>/ ${r.budget.toFixed(2)}</span></div><div className="budget-track"><span style={{width:`${Math.min(100,r.cost/r.budget*100)}%`}}/></div><p className="small-note">已用成本 / 任务预算上限</p><dl><dt>运行耗时</dt><dd>{r.duration}</dd><dt>Tokens</dt><dd>{r.tokens.toLocaleString()}</dd></dl></section><section className="inspector-section"><h3>检查点</h3><p className="mono wrap">{r.checkpoint.id}</p><p>{r.checkpoint.workspace?'工作区已保存':'工作区不可用'}</p><button className="text-action" onClick={()=>rt.setTab('recovery')}>查看恢复条件<ArrowUpRight size={14}/></button></section><section className="inspector-section"><h3>固定执行配置</h3><p>{r.snapshot.model}</p><p className="small-note">{r.snapshot.skills.length} 项技能 · 产物 v{r.version}</p><button className="text-action" onClick={()=>rt.setTab('context')}>检查上下文<ArrowUpRight size={14}/></button></section></div>;
 return <div className="inspector-content"><div className="inspector-heading"><span>项目概况</span><Project size={17}/></div><section className="inspector-section"><span className="project-avatar"><Project size={24}/></span><h3>{rt.route.project==='所有项目'?'全部项目':rt.route.project}</h3><p>{runs.length} 个任务 · {runs.filter(r=>r.status==='SUCCEEDED').length} 个已验证完成</p><div className="health-line"><span/>本地工作空间可用</div></section><section className="inspector-section"><h3>需要关注<span className="count-pill">{urgent.length}</span></h3>{urgent.slice(0,3).map(r=><button className="inspector-task" key={r.id} onClick={()=>rt.openTask(r.id,nextStep(r).tab)}><span className={`mini-dot ${r.status==='FAILED'?'red':'amber'}`}/><span>{r.title}<small>{r.waitReason?waitLabels[r.waitReason]:r.phase}</small></span><ChevronRight size={15}/></button>)}{!urgent.length&&<p>没有待处理阻塞。</p>}</section><section className="inspector-section"><h3>资源使用</h3><div className="budget-value"><strong>${total.toFixed(2)}</strong><span>累计成本</span></div><dl><dt>并发配置</dt><dd>{rt.app.settings.concurrency} 个任务</dd><dt>新任务默认预算</dt><dd>${rt.app.settings.budget.toFixed(2)}</dd></dl><button className="text-action" onClick={()=>rt.app.navigate('observability')}>查看运行分析<ArrowUpRight size={14}/></button></section><section className="inspector-section"><h3>最近交付</h3>{runs.filter(r=>r.status==='SUCCEEDED').slice(0,2).map(r=><button className="inspector-task" key={r.id} onClick={()=>rt.openTask(r.id,'verification')}><CheckCircle2 size={16} className="success-text"/><span>{r.title}<small>凭证绑定 v{r.version}</small></span></button>)}</section><div className="inspector-foot"><ShieldCheck size={15}/><span>持久运行时<br/>执行记录与证据保存在服务端</span></div></div>
}

